### ISSUE TITLE
Requirements / Feasibility Analysis

### ISSUE THREAD

**Issue by abebeos** [abebeos/dolphin-uwp#1]
### Must

* Target: Xbox console
  - [ ]  if it works on UWP, does it work on Xbox?

### Should

* Solution can be easily applied to new versions of original dolphin
  - [ ] what is the original dolphin code? 

## Tasks

- [ ] Brute Force Process: just start with the port, file issues and tasks for contributors of different skill level.

## Estimated Effort
